name: (CI) Flask Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - homolog
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Run Tests
      #   run: |
      #     python manage.py test